### ISSUE TITLE
moveTo 跳转不了指定的index页面

### ISSUE THREAD

**Issue by claire1028** [littledu/PageSlider#2]

**Comment by littledu** [comment]
1. 是否能正常跑起来
2. 具体代码是否可以放出来我看看？
3. 我 demo 的页面测试 moveTo 跳转正常哦

**Comment by claire1028** [comment]
能正常跑起来，就是跳不了指定的页面，
 var page =  new PageSlider({
          pages: $('.page-wrap .page'),
          onSwipeUp: function () {
                  if(this.index == 1){
                     this.moveTo(3);
                  },    
        });

**Comment by claire1028** [comment]
其实我想要的效果是，如果中间有几张页面是display：none 的，想直接跳过去，有什么好的建议吗？

**Comment by littledu** [comment]
```
var page = new PageSlider({
        pages: $('.page-wrap .page'),
});
```

如上代码，pageSlider 的调用方式是自己控制的，如果你中间有是隐藏的，你可以通过改变他的 class，如 page 改成 hide，通过 class 控制其隐藏，那么，就不会被获取了;如果你一定要用 style="display:none" 的方式，你也可以自己写代码过滤掉隐藏的元素，只要你传过来的 pages 参数是显示的即可。

**Comment by claire1028** [comment]
意思是如果class上没有page这个类，就不会被获取了是吗，还是需要再隐藏这个div？如下class=test这样
<div class="page-wrap">
    <div class="page">
        <div class="title">page one</div>
    </div>
  <div class="test">jkkk</div>
    <div class="page" >
       <div class="title">page two</div>
    </div>

**Comment by littledu** [comment]
是啊，这些都是很自由控制的，你 class="page" 的去掉，就不会被获取了，改成其他，如 class="hide", 然后通过

```
.hide{
    display: none;
}
```

来实现隐藏，就 OK 了。
