### ISSUE TITLE
有没有办法知道即将滑动到下一页的index？

### ISSUE THREAD

**Issue by claire1028** [littledu/PageSlider#4]

**Comment by littledu** [comment]
在 onchange 方法里面可以知道 this.index 当前页面的索引，那么，this.index+1 就是下一页，this.index-1 就是上一页

**Comment by claire1028** [comment]
那在onbeforechange方法里面能知道即将滑动到的下一页的index吗？我希望能在滑动到某一页之前把某些元素给隐藏掉

**Comment by littledu** [comment]
你的某一页肯定是固定的某一页对不对，那么，你可以在 onSwipeUp 和 onSwipeDown 方法里面判断：
假设某一页是 3
```javascript
new PageSlider({
    pages: $('.page-wrap .page'),
    onSwipeUp: function(){
        if(this.index+1 === 3){
               //ooxx.style.display = 'none';
        }
   },
   onSwipeDown: function(){
        if(this.index-1 === 3){
               //ooxx.style.display = 'none';
        }
   }
});
```

**Comment by claire1028** [comment]
赞，非常感谢，请接受小白的膝盖

**Comment by claire1028** [comment]
还有个问题，如果这页内容很长的话，岂不是还没滑动到下一页，在向上滑动的时候就把某些元素给隐藏了？

**Comment by littledu** [comment]
所以有一个长页面的需求

**Comment by claire1028** [comment]
"我希望能在滑动到某一页之前把某些元素给隐藏掉'",你给的建议是：
 onSwipeUp: function(){
        if(this.index+1 === 3){
               //ooxx.style.display = 'none';
        }
如果当前在index = 2的页面上，并且该页面是个长页面的话,岂不是向上滑动的时候，某些元素就隐藏了，如果我希望在跳转到另一页的时候才隐藏，在长页面向上滑动的时候不希望隐藏它，该怎么办呢？

**Comment by littledu** [comment]
你再加一个判断不就行了？如果当前页是长页面，就不隐藏

**Comment by claire1028** [comment]
没太明白，那如何区分滑动的时候是当前页滑动还是跳到下一页的滑动呢？
