### ISSUE TITLE
关于长页面的高度问题

### ISSUE THREAD

**Issue by claire1028** [littledu/PageSlider#5]

**Comment by claire1028** [comment]
“-webkit-overflow-scrolling: touch;” 必须要给它一个固定的超出屏幕的高度才会出现滚动条，那如果我的某一个页面的内容是动态的，有时候可能没超出屏幕大小，所以就不需要滚动条，可有时候内容很长的话就需要滚动条出现，这个改怎么办呢？

**Comment by littledu** [comment]
这一个没办法，在这种滚动的页面里面，我需要知道一个确切的高度来判断是不是长页面，你的内容不固定，只能在调用 pageSlider 之前，先自己动态计算一下这个内容的长度，然后再调用 pageSlider

**Comment by claire1028** [comment]
好的，感谢了
