### ISSUE TITLE
从Android app里面内嵌的浏览器打开为何滚动不了而且翻不了页，是兼容问题吗？ios可以的

### ISSUE THREAD

**Issue by claire1028** [littledu/PageSlider#6]

**Comment by littledu** [comment]
什么手机，什么 系统，什么地址

**Comment by claire1028** [comment]
华为的，4.04的，木有地址。。。自己弄的一个demo，我自己debug了一下，好像没有触发touchend事件

**Comment by littledu** [comment]
华为的机子之前也是有做过测试的，当时没有发现问题，你看看其他安卓手机是否有问题，有的话如果方便可以打包一下代码发我，410491325@qq.com

**Comment by claire1028** [comment]
我把在监听touch事件的时候，'this.target.on'变为$('body').bind就好了,这样会不会造成其他的影响啊？

**Comment by littledu** [comment]
this.targe 只是当前元素，$('body') 则是全局，在这里一样的，因为每一屏都是撑满 满屏

**Comment by claire1028** [comment]
好的，多谢
